export const pubData = [
  {
    id: 0,
    titulo: "Desenvolvimento planejado? O destino da Amazônia frente aos investimentos em sua modernização",
    autores: ["Maria Dolores Lima da Silva"],
    orientação: [""],
    pesquisadores: [""],
    data: "2025",
    tipo: "capítulo_de_livro",
    resumo: "A partir de estudos bibliográficos se observa, desde o século xix a exploração econômica extrativa alimentava a opulência das elites políticas e econômicas regionais esetores comerciais externos à região. De meados do século xx em diante, uma nova perspectiva de desenvolvimento se delineou para a região, que vai se afirmar a partirda ação dos governos militares na década de 1960. O Estado brasileiro elaborou um projeto para a integração regional com o propósito de inseri-la em modernas relações econômicas de produção. Os conflitos advindos dos impactos socioambientais, gerados em função do contraste entre formas de vida tradicionais e as novas práticas e interessesde uso da terra e seus recursos, são apontados como um problema ainda sem solução.Até o contexto atual não se apresentaram alternativas produtivas que representem uma mudança no destino traçado para a Amazônia como fornecedora de produtos naturais.O cenário político interno é desfavorável ao enfrentamento desses problemas e apontapara uma reversão das conquistas alcançadas nas duas últimas décadas em benefícioda preservação ambiental e do reconhecimento de direitos às populações tradicionais.",
    link: "https://cebusal.es/wp-content/uploads/2025/09/La-proteccion-del-medioambiente.pdf#page=54.99",
    imagem: 'assets/publications/pub0.png',
    comocitar: 'Silva, Maria Dolores L.  (2025) Desenvolvimento planejado? O destino da Amazônia frente aos investimentos em sua modernizaçãp In: La protección del medio ambiente y las políticas de desarrollo enla Amazonia brasileña, ed.1. Salamanca - Espãna: Ediciones Universidad de Salamanca, v.1, p. 55 -72.',
  },
  {
    id: 1,
    titulo: "Opportunities and strategies of the  dismantling process of Brazilian environmental policy: Forests and indigenous populations under attack",
    autores: ["Maria Dolores Lima da Silva", "Ana Luiza M. Medeiros"],
    orientação: [""],
    pesquisadores: [""],
    data: "2024",
    tipo: "capítulo_de_livro",
    resumo: "ATUALIZAR",
    link: "https://www.taylorfrancis.com/books/edit/10.4324/9781003487777/social-policies-times-austerity-populism-nat%C3%A1lia-s%C3%A1tyro?refId=643a5fc6-f3c2-489c-b2cd-418a7c4913a3&context=ubx",
    imagem: 'assets/publications/pub1.png',
    comocitar: 'Silva, Maria Dolores L.; Medeiros, Ana Luiza M. (2024) Opportunities and strategies of the  dismantling process of Brazilian environmental policy: Forests and indigenous populations under attack In: Sátyro, Natália (edit.) Social Policies in Times of Austerity and Populism Lessons from Brazil., ed.1ª. New York: Routledge, v.1, p. 301 - 327.',
  },
  {
    id: 2,
    titulo: "Governabilidade e políticas públicas: uma análise da questão ambiental",
    autores: ["Maria Dolores Lima da Silva", "Ivan H. M. E. Silva"],
    orientação: [""],
    pesquisadores: [""],
    data: "2023",
    tipo: "capítulo_de_livro",
    resumo: "Neste capítulo analisaremos as possibilidades do sucesso da pauta ambiental dentro da estrutura de governabilidade do presidencialismo de coalizão brasileiro,destacando a mudança de trajetória verificada durante o governo Bolsonaro (2019-2022) e a sucessiva expectativa criada na opinião pública, com a eleição de Lula da Silva (2023-atual), a respeito dessa temática. A questão ambiental assumiu o centro do debate público nos últimos anos, em especial a partir de 2018, em duas chaves diametralmente opostas, que podem ser definidas na chave do antiambientalismo bolsonarista e do ambientalismo defendido pelo campo lulista (SILVA; TESTON, 2023). A partir de uma análise histórica da política ambiental desde a  redemocratização,identificamos as forças políticas que resistem ao rigor das políticas ambientais eanalisamos as possibilidades de avanço dessa  agenda. Essa temática se constituiu em importante dimensão de legitimidade no terceiro mandato de Lula, em contraposição ao governo Bolsonaro que apresentava sua política de desmantelamento como um pedido de crédito a importantes grupos econômicos que se opõem às políticas ambientais. A partir dos fundamentos institucionais que asseguram a estabilidade dos mandatos presidenciais, analisaremos o papel da preferência por políticas públicas na manutenção da estabilidade governamental. Dividiremos o capítulo em três partes, além desta introdução e das consideraçõesfinais. Na próxima parte apresentaremos o referencial teórico de análise, que aborda as condições de governabilidade das instituições políticas brasileiras. Em seguida mostramos como foi estruturado o sistema de proteção ambiental no Brasil, apontando que a política dos últimos anos visou inviabilizar os controles e o funcionamento regular das instituições ambientais; pontuamos o retorno de Lula ao poder prometendo retomar a agenda ambiental.Na última parte identificamos forças políticas presentes na estruturação do terceirogoverno Lula, mostrando como a formação de sua base de apoio partidário impacta na efetividade e no alcance de ações e políticas de proteção ambiental. Sustentamos que, considerando as preferências dos partidos que fazem parte da coalizão de governo, na atual gestão, Lula terá que negociar modificações em matérias regulatórias que podem retirar o rigor da legislação.Nas considerações finais observamos que, na configuração de poder sob a qual agovernabilidade do atual presidente se sustenta, a agenda ambiental terá que ser negociada e alterada para atender a interesses dos membros da coalizão, cujos atores políticos mais fortes se posicionam de forma oposta ao partido do presidente e a seus aliados à esquerda do espectro político.",
    link: "https://www.kas.de/documents/265553/265602/Governabilidade+-+segunda+edi%C3%A7%C3%A3o_DIGITAL.pdf/c81b1c0e-82ba-3178-2d4d-a730418fda05?version=1.0&t=1709315423519",
    imagem: 'assets/publications/pub2.png',
    comocitar: 'Silva, Maria Dolores L.; SILVA, Ivan H. M. E.  (2023) Governabilidade e políticas públicas: uma análise da questão ambiental In: Governabilidade - instituições, atores e estratégias, ed.1. Rio de Janeiro: Konrad Adenauer Stiftung, v.2, p. 229 - 250.',
  },
  {
    id: 3,
    titulo: "Os desafios socioambientais da construção de hidrelétricas na Amazônia: os casos dos municípios de Tucuruí e Altamira no estado do Pará",
    autores: ["Maria Dolores Lima da Silva", "Diego Brilhante Athayde", "Jonas Guilherme Figueiredo da Trindade", "João Elbio de Oliveira Aquino Sequeira"],
    orientação: [""],
    pesquisadores: [""],
    data: "2022",
    tipo: "artigo",
    resumo: "O  objetivo  desse  artigo  é  verificar  as  características  socioambientais  que  os municípios de Tucuruí e Altamira apresentam ao longo de três décadas, relacionando-as com a construção das hidrelétricas em seus territórios. A escolha desses dois munícipios se deu pelo fato de que a hidrelétrica de Tucuruí (UHT) e de Belo Monte (UHBM), em Altamira, foram  construídas  em  contextos histórico-políticos diferentes, a  UHT  durante  o  regime militar e a UHBM em um contexto democrático. Usamos indicadores oficiais, do IBGE, IPEA,  entre  outros,  para  conduzir  uma  reflexão  que  questiona  se  o  fato  dessas  duas hidrelétricas terem sido construídas em contextos diferentes faz diferença para a qualidade de vida da população desses municípios. Essa avaliação é guiada pela reflexão a respeito da concepção de desenvolvimento e do papel das políticas públicas na mitigação dos impactos da construção de hidrelétricas na Amazônia.",
    link: "https://www.researchgate.net/publication/358079911_desafios_socioambientais_da_construcao_de_hidreletricas_na_Amazonia_os_casos_dos_municipios_de_Tucurui_e_Altamira_no_estado_do_Para_os_casos_dos_municipios_de_Tucurui_e_Altamira_no_estado_do_Para#read",
    imagem: 'assets/publications/pub3.png',
    comocitar: 'Silva, Dolores; Brilhante, Diego A; Trindade, Jonas G. F.; Sequeira, João E. O. A. (2022) Desafios socioambientais da construção de hidrelétricas na Amazônia: os casos dos municípios de Tucuruí e Altamira no estado do Pará. Campos Neutrais - Revista Latino-Americana de Relações Internacionais. v.3, p.31 - 51.',
  },
  {
    id: 4,
    titulo: "A Amazônia e o desenvolvimento: aspectos da trajetória das políticas públicas na região",
    autores: ["Maria Dolores Lima da Silva"],
    orientação: [""],
    pesquisadores: [""],
    data: "2021",
    tipo: "artigo",
    resumo: "Este artigo faz uma avaliação das políticas públicas de desenvolvimento que foram planejadas para a Amazônia a partir da década de 1950 e materializadas, especialmente, da década de 1970 em diante. A exploração econômica fomentada não resultou em aumento significativo do bem-estar social da população. Como base dessa argumentação, são utilizados estudos bibliográficos e pesquisas em sites de instituições públicas e de Organizações Não Governamentais. Os registros de pesquisadores e entidades que atuam na região mostram que as populações tradicionais padecem com a desestruturação de seus modos de vida e que os conflitos gerados se estendem através de décadas, permanecendo sem solução.",
    link: "https://www.researchgate.net/publication/358079911_desafios_socioambientais_da_construcao_de_hidreletricas_na_Amazonia_os_casos_dos_municipios_de_Tucurui_e_Altamira_no_estado_do_Para_os_casos_dos_municipios_de_Tucurui_e_Altamira_no_estado_do_Para#read",
    imagem: 'assets/publications/pub4.png',
    comocitar: 'SILVA, Maria Dolores L. (2021) La Amazonía y el desarrollo: aspectos de la trayectoria de las políticas públicas en la región. Revista de Estudios de Estudios Brasileños. v.7, p.219 – 232.',
  },
]