export const pubData = [
  {
    id: 0,
    titulo: "Desenvolvimento planejado? O destino da Amazônia frente aos investimentos em sua modernização",
    autores: ["Maria Dolores Lima da Silva"],
    orientação: [""],
    pesquisadores: [""],
    data: "2025",
    tipo: "capítulo_de_livro",
    resumo: "A partir de estudos bibliográficos se observa, desde o século xix a exploração econômica extrativa alimentava a opulência das elites políticas e econômicas regionais esetores comerciais externos à região. De meados do século xx em diante, uma nova perspectiva de desenvolvimento se delineou para a região, que vai se afirmar a partirda ação dos governos militares na década de 1960. O Estado brasileiro elaborou um projeto para a integração regional com o propósito de inseri-la em modernas relações econômicas de produção. Os conflitos advindos dos impactos socioambientais, gerados em função do contraste entre formas de vida tradicionais e as novas práticas e interessesde uso da terra e seus recursos, são apontados como um problema ainda sem solução.Até o contexto atual não se apresentaram alternativas produtivas que representem uma mudança no destino traçado para a Amazônia como fornecedora de produtos naturais.O cenário político interno é desfavorável ao enfrentamento desses problemas e apontapara uma reversão das conquistas alcançadas nas duas últimas décadas em benefícioda preservação ambiental e do reconhecimento de direitos às populações tradicionais.",
    link: "https://cebusal.es/wp-content/uploads/2025/09/La-proteccion-del-medioambiente.pdf#page=54.99",
    imagem: 'assets/publications/artigosalamanca.png',
    comocitar: 'Silva, Maria Dolores L.  (2025) Desenvolvimento planejado? O destino da Amazônia frente aos investimentos em sua modernizaçãp In: La protección del medio ambiente y las políticas de desarrollo enla Amazonia brasileña, ed.1. Salamanca - Espãna: Ediciones Universidad de Salamanca, v.1, p. 55 -72.',
  },
  {
    id: 1,
    titulo: "Opportunities and strategies of the  dismantling process of Brazilian environmental policy: Forests and indigenous populations under attack",
    autores: ["Maria Dolores Lima da Silva", "Ana Luiza M. Medeiros"],
    orientação: [""],
    pesquisadores: [""],
    data: "2024",
    tipo: "capítulo_de_livro",
    resumo: "A partir de estudos bibliográficos se observa, desde o século xix a exploração eco-nômica extrativa alimentava a opulência das elites políticas e econômicas regionais esetores comerciais externos à região. De meados do século xx em diante, uma novaperspectiva de desenvolvimento se delineou para a região, que vai se afirmar a partirda ação dos governos militares na década de 1960. O Estado brasileiro elaborou umprojeto para a integração regional com o propósito de inseri-la em modernas relaçõeseconômicas de produção. Os conflitos advindos dos impactos socioambientais, geradosem função do contraste entre formas de vida tradicionais e as novas práticas e interessesde uso da terra e seus recursos, são apontados como um problema ainda sem solução.Até o contexto atual não se apresentaram alternativas produtivas que representem uma mudança no destino traçado para a Amazônia como fornecedora de produtos naturais.O cenário político interno é desfavorável ao enfrentamento desses problemas e apontapara uma reversão das conquistas alcançadas nas duas últimas décadas em benefícioda preservação ambiental e do reconhecimento de direitos às populações tradicionais.",
    link: "https://www.taylorfrancis.com/books/edit/10.4324/9781003487777/social-policies-times-austerity-populism-nat%C3%A1lia-s%C3%A1tyro?refId=643a5fc6-f3c2-489c-b2cd-418a7c4913a3&context=ubx",
    imagem: 'assets/publications/artigosocialpolicies.png',
    comocitar: 'Silva, Maria Dolores L.; Medeiros, Ana Luiza M. (2024) Opportunities and strategies of the  dismantling process of Brazilian environmental policy: Forests and indigenous populations under attack In: Sátyro, Natália (edit.) Social Policies in Times of Austerity and Populism Lessons from Brazil., ed.1ª. New York: Routledge, v.1, p. 301 - 327.',
  },
]